notifications:
    webhooks:
        - secure: "JcXvV3fY/mIJ0ABqxp4ztSQQXsYhfbbfJaFzZfQ0AYCEZYD0jze7V+DorFOhXkyRgO6n57QaAIdsFmMjJHm3TuICTpWJEyi7cn7E2BhqyaPD3YNAR2vd2SWBNKyH3bAKJWyCf5g5uewVNgk2+y3vIhkEE3CnKBesld/Z5s7Axkc="

language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

install:
    - "python setup.py install"
    - "pip install pyte coverage"

script:
    - nosetests tests
